type=adape
torchrun --master_port 29516 --nproc_per_node=4 train_longlora.py  \
        --ddp_timeout 18000 \
        --model_name_or_path meta-llama/Llama-2-7b-hf \
        --resume_from_checkpoint false \
        --peft_type $type \
        --bf16 true \
        --output_dir ./output/llama_${type} \
        --model_max_length 8192 \
        --use_flash_attn true \
        --per_device_train_batch_size 1     \
        --per_device_eval_batch_size 2     \
        --gradient_accumulation_steps 8     \
        --evaluation_strategy "no"     \
        --save_strategy "steps"     \
        --save_steps 200     \
        --save_total_limit 2     \
        --learning_rate 2e-5     \
        --weight_decay 0.0     \
        --warmup_steps 50     \
        --lr_scheduler_type "constant_with_warmup"     \
        --logging_steps 10     \
        --deepspeed "config/ds_configs/stage2.json" \
        --tf32 true \
        --report_to none \
        --max_steps 2000 > log/train_llama_${type}.log 2>&1 &
